"""Convert PostgreSQL UUID columns to generic Uuid type for SQLite compatibility

Revision ID: 4e33f7897757
Revises: 5722cbbf8ed5
Create Date: 2025-09-20 14:46:40.367421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4e33f7897757'
down_revision = '5722cbbf8ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_interval_configs')
    op.drop_index('idx_portfolio_update_metrics_created_status', table_name='portfolio_update_metrics')
    op.drop_index('idx_portfolio_update_metrics_performance', table_name='portfolio_update_metrics')
    op.drop_index('idx_portfolio_update_metrics_portfolio_status', table_name='portfolio_update_metrics')
    op.drop_index('idx_portfolio_update_metrics_trigger_type', table_name='portfolio_update_metrics')
    op.drop_index('ix_portfolio_update_metrics_created_at', table_name='portfolio_update_metrics')
    op.drop_index('ix_portfolio_update_metrics_error_type', table_name='portfolio_update_metrics')
    op.drop_index('ix_portfolio_update_metrics_portfolio_id', table_name='portfolio_update_metrics')
    op.drop_index('ix_portfolio_update_metrics_status', table_name='portfolio_update_metrics')
    op.drop_index('ix_portfolio_update_metrics_trigger_type', table_name='portfolio_update_metrics')
    op.drop_table('portfolio_update_metrics')
    op.drop_index('ix_sse_connections_connection_id', table_name='sse_connections')
    op.drop_index('ix_sse_connections_user_id', table_name='sse_connections')
    op.drop_table('sse_connections')
    op.drop_index('ix_scheduler_executions_id', table_name='scheduler_executions')
    op.drop_index('ix_scheduler_executions_started_at', table_name='scheduler_executions')
    op.drop_index('ix_scheduler_executions_status', table_name='scheduler_executions')
    op.drop_table('scheduler_executions')
    op.drop_index('idx_portfolio_queue_metrics_created', table_name='portfolio_queue_metrics')
    op.drop_index('idx_portfolio_queue_metrics_performance', table_name='portfolio_queue_metrics')
    op.drop_index('idx_portfolio_queue_metrics_processing', table_name='portfolio_queue_metrics')
    op.drop_index('ix_portfolio_queue_metrics_created_at', table_name='portfolio_queue_metrics')
    op.drop_table('portfolio_queue_metrics')
    op.alter_column('adapter_health_checks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('adapter_health_checks', 'provider_config_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('adapter_registry', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('cost_tracking_records', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('cost_tracking_records', 'provider_config_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('market_data_usage_metrics', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('market_data_usage_metrics', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('market_data_usage_metrics', 'portfolio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('provider_configurations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('provider_configurations', 'created_by_user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('provider_metrics', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('provider_metrics', 'provider_config_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_symbols', 'provider_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_symbols', 'latest_history_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtime_symbols', 'latest_history_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('realtime_symbols', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_metrics', 'provider_config_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_configurations', 'created_by_user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_configurations', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('market_data_usage_metrics', 'portfolio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('market_data_usage_metrics', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('market_data_usage_metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('cost_tracking_records', 'provider_config_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('cost_tracking_records', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('adapter_registry', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('adapter_health_checks', 'provider_config_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('adapter_health_checks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('portfolio_queue_metrics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pending_updates', sa.INTEGER(), nullable=False),
    sa.Column('processing_rate', sa.NUMERIC(precision=8, scale=2), nullable=False),
    sa.Column('active_portfolios', sa.INTEGER(), nullable=False),
    sa.Column('avg_processing_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('max_processing_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('queue_throughput', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('rate_limit_hits', sa.INTEGER(), nullable=False),
    sa.Column('coalesced_updates', sa.INTEGER(), nullable=False),
    sa.Column('debounce_savings', sa.INTEGER(), nullable=False),
    sa.Column('memory_usage_mb', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.Column('cpu_usage_percent', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('database_connections', sa.INTEGER(), nullable=True),
    sa.Column('is_processing', sa.BOOLEAN(), nullable=False),
    sa.Column('last_successful_update', sa.DATETIME(), nullable=True),
    sa.Column('error_count_last_hour', sa.INTEGER(), nullable=False),
    sa.Column('debounce_seconds', sa.NUMERIC(precision=4, scale=1), nullable=True),
    sa.Column('max_updates_per_minute', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_queue_metrics_created_at', 'portfolio_queue_metrics', ['created_at'], unique=False)
    op.create_index('idx_portfolio_queue_metrics_processing', 'portfolio_queue_metrics', ['is_processing', 'created_at'], unique=False)
    op.create_index('idx_portfolio_queue_metrics_performance', 'portfolio_queue_metrics', ['processing_rate', 'pending_updates'], unique=False)
    op.create_index('idx_portfolio_queue_metrics_created', 'portfolio_queue_metrics', ['created_at'], unique=False)
    op.create_table('scheduler_executions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('symbols_processed', sa.INTEGER(), nullable=True),
    sa.Column('successful_fetches', sa.INTEGER(), nullable=True),
    sa.Column('failed_fetches', sa.INTEGER(), nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('provider_used', sa.VARCHAR(length=50), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('execution_metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_executions_status', 'scheduler_executions', ['status'], unique=False)
    op.create_index('ix_scheduler_executions_started_at', 'scheduler_executions', ['started_at'], unique=False)
    op.create_index('ix_scheduler_executions_id', 'scheduler_executions', ['id'], unique=False)
    op.create_table('sse_connections',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.NUMERIC(), nullable=False),
    sa.Column('client_ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('subscribed_symbols', sqlite.JSON(), nullable=True),
    sa.Column('portfolio_ids', sqlite.JSON(), nullable=True),
    sa.Column('connection_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_heartbeat', sa.DATETIME(), nullable=True),
    sa.Column('messages_sent', sa.INTEGER(), nullable=False),
    sa.Column('connected_at', sa.DATETIME(), nullable=False),
    sa.Column('disconnected_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sse_connections_user_id', 'sse_connections', ['user_id'], unique=False)
    op.create_index('ix_sse_connections_connection_id', 'sse_connections', ['connection_id'], unique=1)
    op.create_table('portfolio_update_metrics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('portfolio_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('symbols_updated', sqlite.JSON(), nullable=False),
    sa.Column('symbols_count', sa.INTEGER(), nullable=False),
    sa.Column('update_duration_ms', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('update_source', sa.VARCHAR(length=30), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('error_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('queue_wait_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('db_query_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('calculation_time_ms', sa.INTEGER(), nullable=True),
    sa.Column('coalesced_count', sa.INTEGER(), nullable=True),
    sa.Column('debounce_delay_ms', sa.INTEGER(), nullable=True),
    sa.Column('price_change_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('queue_entry_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('processing_start_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_update_metrics_trigger_type', 'portfolio_update_metrics', ['trigger_type'], unique=False)
    op.create_index('ix_portfolio_update_metrics_status', 'portfolio_update_metrics', ['status'], unique=False)
    op.create_index('ix_portfolio_update_metrics_portfolio_id', 'portfolio_update_metrics', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_update_metrics_error_type', 'portfolio_update_metrics', ['error_type'], unique=False)
    op.create_index('ix_portfolio_update_metrics_created_at', 'portfolio_update_metrics', ['created_at'], unique=False)
    op.create_index('idx_portfolio_update_metrics_trigger_type', 'portfolio_update_metrics', ['trigger_type', 'created_at'], unique=False)
    op.create_index('idx_portfolio_update_metrics_portfolio_status', 'portfolio_update_metrics', ['portfolio_id', 'status'], unique=False)
    op.create_index('idx_portfolio_update_metrics_performance', 'portfolio_update_metrics', ['update_duration_ms', 'status'], unique=False)
    op.create_index('idx_portfolio_update_metrics_created_status', 'portfolio_update_metrics', ['created_at', 'status'], unique=False)
    op.create_table('poll_interval_configs',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('interval_minutes', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('expired_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###