"""Add admin service audit event types for provider and scheduler control

Revision ID: 87d26aebac93
Revises: 42d56891bcef
Create Date: 2025-09-15 16:19:42.033127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d26aebac93'
down_revision = '42d56891bcef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage_metrics')
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.Enum('PORTFOLIO_CREATED', 'PORTFOLIO_UPDATED', 'PORTFOLIO_DELETED', 'PORTFOLIO_SOFT_DELETED', 'PORTFOLIO_HARD_DELETED', 'TRANSACTION_CREATED', 'TRANSACTION_UPDATED', 'TRANSACTION_DELETED', 'HOLDING_CREATED', 'HOLDING_UPDATED', 'HOLDING_DELETED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'ADMIN_ACTION_PERFORMED', 'PROVIDER_ENABLED', 'PROVIDER_DISABLED', 'PROVIDER_PAUSED', 'PROVIDER_RESUMED', 'PROVIDER_CONFIGURED', 'SCHEDULER_STARTED', 'SCHEDULER_STOPPED', 'SCHEDULER_PAUSED', 'SCHEDULER_RESUMED', 'SCHEDULER_CONFIGURED', 'SYSTEM_MAINTENANCE_START', 'SYSTEM_MAINTENANCE_END', name='auditeventtype'),
               existing_nullable=False)
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.Uuid(),
               nullable=False)
    op.alter_column('transactions', 'portfolio_id',
               existing_type=sa.TEXT(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('transactions', 'stock_id',
               existing_type=sa.TEXT(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('BUY', 'SELL', 'DIVIDEND', 'STOCK_SPLIT', 'REVERSE_SPLIT', 'TRANSFER_IN', 'TRANSFER_OUT', 'SPIN_OFF', 'MERGER', 'BONUS_SHARES', name='transactiontype'),
               existing_nullable=False)
    op.alter_column('transactions', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('EMAIL', 'MANUAL', 'API', name='sourcetype'),
               existing_nullable=False)
    op.alter_column('transactions', 'source_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'broker_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('transactions', 'transaction_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_timestamp', sa.DATETIME(), nullable=True))
    op.alter_column('transactions', 'broker_reference',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'source_reference',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'source_type',
               existing_type=sa.Enum('EMAIL', 'MANUAL', 'API', name='sourcetype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum('BUY', 'SELL', 'DIVIDEND', 'STOCK_SPLIT', 'REVERSE_SPLIT', 'TRANSFER_IN', 'TRANSFER_OUT', 'SPIN_OFF', 'MERGER', 'BONUS_SHARES', name='transactiontype'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'stock_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'portfolio_id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('transactions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.Enum('PORTFOLIO_CREATED', 'PORTFOLIO_UPDATED', 'PORTFOLIO_DELETED', 'PORTFOLIO_SOFT_DELETED', 'PORTFOLIO_HARD_DELETED', 'TRANSACTION_CREATED', 'TRANSACTION_UPDATED', 'TRANSACTION_DELETED', 'HOLDING_CREATED', 'HOLDING_UPDATED', 'HOLDING_DELETED', 'USER_LOGIN', 'USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'ADMIN_ACTION_PERFORMED', 'PROVIDER_ENABLED', 'PROVIDER_DISABLED', 'PROVIDER_PAUSED', 'PROVIDER_RESUMED', 'PROVIDER_CONFIGURED', 'SCHEDULER_STARTED', 'SCHEDULER_STOPPED', 'SCHEDULER_PAUSED', 'SCHEDULER_RESUMED', 'SCHEDULER_CONFIGURED', 'SYSTEM_MAINTENANCE_START', 'SYSTEM_MAINTENANCE_END', name='auditeventtype'),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False)
    op.create_table('api_usage_metrics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('metric_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('portfolio_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('requests_count', sa.INTEGER(), nullable=True),
    sa.Column('data_points_fetched', sa.INTEGER(), nullable=True),
    sa.Column('cost_estimate', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('time_bucket', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rate_limit_hit', sa.BOOLEAN(), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('avg_response_time_ms', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###