"""Add comprehensive price data fields for trend calculations and market analysis

Revision ID: 88ff55aea2fa
Revises: 87d26aebac93
Create Date: 2025-09-15 20:12:46.265547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ff55aea2fa'
down_revision = '87d26aebac93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - but modified for SQLite compatibility ###
    # Only add new columns to realtime_price_history table for trend calculations
    # Skip problematic ALTER COLUMN operations that are incompatible with SQLite

    op.add_column('realtime_price_history', sa.Column('opening_price', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('previous_close', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('fifty_two_week_high', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('fifty_two_week_low', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('realtime_price_history', sa.Column('dividend_yield', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('realtime_price_history', sa.Column('pe_ratio', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('realtime_price_history', sa.Column('beta', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('realtime_price_history', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('realtime_price_history', sa.Column('company_name', sa.String(length=255), nullable=True))

    # Create index for trend calculations
    op.create_index('idx_symbol_opening_price', 'realtime_price_history', ['symbol', 'opening_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### Simplified downgrade - only remove columns we added ###
    op.drop_index('idx_symbol_opening_price', table_name='realtime_price_history')
    op.drop_column('realtime_price_history', 'company_name')
    op.drop_column('realtime_price_history', 'currency')
    op.drop_column('realtime_price_history', 'beta')
    op.drop_column('realtime_price_history', 'pe_ratio')
    op.drop_column('realtime_price_history', 'dividend_yield')
    op.drop_column('realtime_price_history', 'fifty_two_week_low')
    op.drop_column('realtime_price_history', 'fifty_two_week_high')
    op.drop_column('realtime_price_history', 'previous_close')
    op.drop_column('realtime_price_history', 'low_price')
    op.drop_column('realtime_price_history', 'high_price')
    op.drop_column('realtime_price_history', 'opening_price')
    # ### end Alembic commands ###