"""Initial migration with UTC timestamps

Revision ID: dee471ac1d9d
Revises: 
Create Date: 2025-09-14 21:42:52.150780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee471ac1d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage_metrics')
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('realtime_price_history', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('realtime_price_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('provider_activities', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'portfolio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('portfolio_valuations', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('market_data_providers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('api_usage_metrics',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('metric_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('portfolio_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('requests_count', sa.INTEGER(), nullable=True),
    sa.Column('data_points_fetched', sa.INTEGER(), nullable=True),
    sa.Column('cost_estimate', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.Column('time_bucket', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rate_limit_hit', sa.BOOLEAN(), nullable=True),
    sa.Column('error_count', sa.INTEGER(), nullable=True),
    sa.Column('avg_response_time_ms', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###